work in progress
SkylineCommunications/Skyline.DataMiner.CICD.Tools.ValidatorErrorsToMarkdown pull request #1
Opened 2023-08-07 12:24 UTC by JarneVynckier

2023-08-07 12:25 UTC, MichielOda requested changes
Feedback!

2023-08-07 12:25 UTC, MichielOda commented on CICD.Tools.ValidatorErrorsToMarkdown/Class1.cs
> +	///
Empty xml comment

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +                name: "--fileLocation",
```suggestion
                name: "--inputFilePath",
```
Better to be consistent input - output    instead of fileLocation and resultLocation.  Using 'filePath" also indicates the tool expects the path to the file.

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +                name: "--resultLocation",
```suggestion
                name: "--outputDirectoryPath",
```

we'll be generating several markdown files. So likely we'll want to ask for a directory path

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +            string checkName = check.Descendants("Name").FirstOrDefault().Value;
Instead of Descendants which can be a heavy call. If you know the exact location of the Name then you'll likely want to do: check?.Element("something")?.Element("somethingElse").Element("Name")?.Value

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +            var templateId = errorMessage.Descendants("Description").FirstOrDefault().Attribute("templateId");
same remark. Better to use ?.Element(...) .
Also this can cause nullreference exception .FirstOrDefault() can be "null" and then .Attribute will throw an exception.

the use of "?." is recommended when parsing xml with XDocument, it will 'short circuit' any "null" it finds and result in a null value assignment instead of an exception.

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +                inputParamsArray = new string[templateInputs.Count()];
```suggestion
                
```
This written in a confusing way. I suggest you make a GetCorrectInput(templateInputs) override that makes the resulting inputParamsArray inside of the method.  It's rather confusing to see 2 assignments to the same variable right next to eachother.

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +            inputParamsArray = GetCorrectInput(inputParams, inputParamsArray);
This will override all the work you did to previously fill in the inputParamsArray with the if-else above here.
I think you probably want to move these lines inside of the else?
Can you double check the logic?

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +                    inputParamsArray[index] = "{" + parameter.Value + "}";
I suggest, if the previous suggestions I made make sense. Then you'll probably want to use List<string> for your result and then .Add( "{" + parameter.Value + "}");  to that list, and return the .ToArray() of that list if you actually want a string array.

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdownTests/XDocCheckHelperTests.cs
> +        public void GetCheckDescriptionTestNoTemplateNoOverride()
```suggestion
        public void GetCheckDescriptionTest_NoTemplate_NoAttributeOverride()
```

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdownTests/XDocCheckHelperTests.cs
> +        public void GetCheckDescriptionTestNoTemplateOverride()
```suggestion
        public void GetCheckDescriptionTest_NoTemplate_AttributeOverride()
```

2023-08-09 15:44 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdownTests/XDocCheckHelperTests.cs
> +        public void GetCheckDescriptionTestTemplateOverride()
```suggestion
        public void GetCheckDescriptionTest_TemplateOverride()
```

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/DescriptionTemplates.cs
> +        /// </summary>
Just a tip for writing method documentation.
You can type in /// above a method and it will pre-generate a correct format of documentation, including input arguments & return.

Also, anytime you want to mention something like a class name or enum name you can type in <see + tab
You can write something like this, for constructors:
Creates an instance of class <see cref="DescriptionTemplates"/>

This has the benefit that if you do a Rename action on the class, it will also rename all the documentation. It also provides linking if you convert this to actual MarkDown.

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/ParseXmlToMarkDown.cs
> +                    Directory.CreateDirectory($@"C:\Validator\{catagoryName}\{checkName}");
as we talked about in person, to split them up between validator errors and major change errors. It might be better to either first filter everything in memory, adding them to two lists and then performing the directory access (saving files) in a second loop.

However, what we didn't discuss, is that this can be bad for total memory usage. If the amount of markdown files is extremely large then holding them in memory might be too  much and cause Out of Memory exceptions (in the absolute worst case). If that is the case, then you're going to want to avoid storing the whole thing in Lists.

 At that point you might be better off with your current loop, but just moving the creation of a directory & saving of the markdown file to the bottom of the inner foreach but adding a if (!Directory.Exists(dirname))Directory.CreateDirectory  check.

This will avoid saving everything to Lists first (avoiding memory issues).

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +                description: "File where the MarkDown text is saved to")
```suggestion
                description: "Directory where the MarkDown files are saved to")
```

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +            rootCommand.SetHandler(Process, inputFilePath);
```suggestion
            rootCommand.SetHandler(Process, inputFilePath, outputDirectoryPath );
```

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +        private static void Process(string fileLocation)
```suggestion
        private static void Process(string inputFilePath, string outputDirectoryPath )
```

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +            XDocument xml = XDocument.Load(fileLocation);
```suggestion
            XDocument xml = XDocument.Load(inputFilePath);
```

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/Program.cs
> +            parser.ConvertToMarkDown();
You'll need to pass along outputDirectoryPath either to the Constructor, to a parser.SaveMarkdown(  or to the parser.ConvertToMarkDown(

2023-08-10 15:29 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +            return warnings[0].Value + Environment.NewLine + Environment.NewLine + warnings[1].Value;
This can cause several exceptions:
nullreference exceptions if errorMessage was null.
nullreference exceptions if "AutoFixWarnings" does not exist.
IndexOutOfRange exceptions if the warnings does not have a length > 1.

You'll need to add some validation here or split up the line in a few with some checks between them.


```
var autoFixWarnings = errorMessage?.Element("AutoFixWarnings");
if(autoFixWarnings == null) return String.Empty;
var warnings = autoFixWarnings..Elements("AutoFixWarning").ToList();
if(warnings.Length<2) return String.Empty;
return warnings[0].Value + Environment.NewLine + Environment.NewLine + warnings[1].Value;
```


something like that would work, (note I wrote this without intellisense, so it might have syntax issues)

2023-08-10 15:35 UTC, janstaelensskyline commented on CICD.Tools.ValidatorErrorsToMarkdownTests/XDocCheckHelperTests.cs
Try adding a few 'bad' XML's in tests, to see if those behave as you expect them to. You want to avoid unhandled exceptions from occurring.

2023-08-11 11:42 UTC, JarneVynckier commented on CICD.Tools.ValidatorErrorsToMarkdown/XDocCheckHelper.cs
> +            return warnings[0].Value + Environment.NewLine + Environment.NewLine + warnings[1].Value;
i changed the way this is done. maybe check this on my next commit.

2023-09-13 07:06 UTC, merged